export interface Recipe {
  id: string;
  name: string;
  description: string;
  image: string;
  cuisine: string;
  time: number;
  servings: number;
  calories: number;
  difficulty: "Einfach" | "Mittel" | "Anspruchsvoll";
  tags: string[];
  ingredients: { name: string; amount: string }[];
  steps: string[];
  rating: number;
  source?: string;
}

export const RECIPES: Recipe[] = [
  {
    id: "1",
    name: "Spaghetti Carbonara",
    description: "Klassische römische Pasta mit cremiger Ei-Pecorino-Sauce und knusprigem Guanciale",
    image: "https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=400&h=300&fit=crop",
    cuisine: "Italienisch",
    time: 25,
    servings: 4,
    calories: 650,
    difficulty: "Mittel",
    tags: ["Pasta", "Klassiker", "Schnell"],
    ingredients: [
      { name: "Spaghetti", amount: "400g" },
      { name: "Guanciale", amount: "150g" },
      { name: "Eier", amount: "4 Stück" },
      { name: "Pecorino Romano", amount: "100g" },
      { name: "Schwarzer Pfeffer", amount: "nach Geschmack" },
      { name: "Salz", amount: "nach Geschmack" },
    ],
    steps: [
      "Spaghetti in reichlich Salzwasser al dente kochen.",
      "Guanciale in einer großen Pfanne bei mittlerer Hitze knusprig braten.",
      "Eier mit geriebenem Pecorino verquirlen, großzügig pfeffern.",
      "Pasta abgießen, dabei etwas Kochwasser auffangen.",
      "Pfanne vom Herd nehmen, Pasta dazugeben, Ei-Mischung einrühren.",
      "Mit Kochwasser cremige Konsistenz erreichen. Sofort servieren.",
    ],
    rating: 4.8,
    source: "Chefkoch",
  },
  {
    id: "2",
    name: "Butter Chicken Curry",
    description: "Zartes Hähnchen in einer aromatischen Tomatenbutter-Sauce mit indischen Gewürzen",
    image: "https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=400&h=300&fit=crop",
    cuisine: "Indisch",
    time: 45,
    servings: 4,
    calories: 580,
    difficulty: "Mittel",
    tags: ["Curry", "Hähnchen", "Glutenfrei"],
    ingredients: [
      { name: "Hähnchenbrust", amount: "600g" },
      { name: "Tomatenpüree", amount: "400ml" },
      { name: "Sahne", amount: "200ml" },
      { name: "Butter", amount: "50g" },
      { name: "Garam Masala", amount: "2 TL" },
      { name: "Kurkuma", amount: "1 TL" },
      { name: "Ingwer", amount: "2 cm" },
      { name: "Knoblauch", amount: "3 Zehen" },
      { name: "Zwiebel", amount: "1 Stück" },
      { name: "Basmati Reis", amount: "300g" },
    ],
    steps: [
      "Hähnchen in Würfel schneiden und mit Joghurt und Gewürzen marinieren.",
      "Zwiebeln, Knoblauch und Ingwer in Butter anbraten.",
      "Hähnchen dazugeben und goldbraun braten.",
      "Tomatenpüree einrühren und 15 Minuten köcheln lassen.",
      "Sahne hinzufügen und weitere 5 Minuten köcheln.",
      "Mit Reis und frischem Koriander servieren.",
    ],
    rating: 4.7,
    source: "HelloFresh",
  },
  {
    id: "3",
    name: "Buddha Bowl mit Quinoa",
    description: "Nährstoffreiche Bowl mit geröstetem Gemüse, Quinoa und Tahini-Dressing",
    image: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=400&h=300&fit=crop",
    cuisine: "International",
    time: 30,
    servings: 2,
    calories: 420,
    difficulty: "Einfach",
    tags: ["Vegetarisch", "Vegan", "Glutenfrei", "Gesund"],
    ingredients: [
      { name: "Quinoa", amount: "200g" },
      { name: "Kichererbsen", amount: "400g (Dose)" },
      { name: "Süßkartoffel", amount: "2 Stück" },
      { name: "Spinat", amount: "100g" },
      { name: "Avocado", amount: "1 Stück" },
      { name: "Tahini", amount: "3 EL" },
      { name: "Zitrone", amount: "1 Stück" },
      { name: "Olivenöl", amount: "2 EL" },
    ],
    steps: [
      "Quinoa nach Packungsanleitung kochen.",
      "Süßkartoffel und Kichererbsen mit Olivenöl und Gewürzen im Ofen rösten.",
      "Tahini mit Zitronensaft und Wasser zu Dressing verrühren.",
      "Bowl zusammenstellen: Quinoa, Gemüse, Spinat und Avocado.",
      "Mit Tahini-Dressing beträufeln und servieren.",
    ],
    rating: 4.5,
    source: "BBC Food",
  },
  {
    id: "4",
    name: "Wiener Schnitzel",
    description: "Goldbraun paniertes Kalbsschnitzel nach Wiener Art mit Preiselbeeren und Pommes",
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=300&fit=crop",
    cuisine: "Österreichisch",
    time: 35,
    servings: 4,
    calories: 780,
    difficulty: "Mittel",
    tags: ["Fleisch", "Klassiker", "Österreich"],
    ingredients: [
      { name: "Kalbsschnitzel", amount: "4 Stück (je 150g)" },
      { name: "Semmelbrösel", amount: "200g" },
      { name: "Mehl", amount: "100g" },
      { name: "Eier", amount: "3 Stück" },
      { name: "Butterschmalz", amount: "200ml" },
      { name: "Zitrone", amount: "1 Stück" },
      { name: "Preiselbeeren", amount: "4 EL" },
      { name: "Salz & Pfeffer", amount: "nach Geschmack" },
    ],
    steps: [
      "Schnitzel zwischen Frischhaltefolie dünn klopfen.",
      "Mehl, verquirlte Eier und Semmelbrösel in separate Schüsseln geben.",
      "Schnitzel salzen, durch Mehl, Ei und Brösel ziehen.",
      "In heißem Butterschmalz goldbraun braten (je 2-3 Min. pro Seite).",
      "Auf Küchenpapier abtropfen lassen.",
      "Mit Zitronenspalten und Preiselbeeren servieren.",
    ],
    rating: 4.9,
    source: "Chefkoch",
  },
  {
    id: "5",
    name: "Avocado Caesar Salad",
    description: "Knackiger Römersalat mit hausgemachtem Caesar-Dressing, Croutons und Parmesan",
    image: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=400&h=300&fit=crop",
    cuisine: "Amerikanisch",
    time: 20,
    servings: 2,
    calories: 380,
    difficulty: "Einfach",
    tags: ["Salat", "Schnell", "Vegetarisch"],
    ingredients: [
      { name: "Römersalat", amount: "1 Kopf" },
      { name: "Avocado", amount: "1 Stück" },
      { name: "Parmesan", amount: "50g" },
      { name: "Croutons", amount: "100g" },
      { name: "Mayonnaise", amount: "3 EL" },
      { name: "Worcestersauce", amount: "1 TL" },
      { name: "Knoblauch", amount: "1 Zehe" },
      { name: "Zitronensaft", amount: "1 EL" },
    ],
    steps: [
      "Römersalat waschen und in Stücke zupfen.",
      "Caesar-Dressing aus Mayo, Worcestersauce, Knoblauch und Zitronensaft mixen.",
      "Avocado halbieren und in Scheiben schneiden.",
      "Salat mit Dressing vermengen.",
      "Avocado, Croutons und Parmesan darauf anrichten.",
    ],
    rating: 4.4,
    source: "BBC Food",
  },
  {
    id: "6",
    name: "Flammkuchen Elsässer Art",
    description: "Hauchdünner Teig mit Crème fraîche, Speck und Zwiebeln aus dem Elsass",
    image: "https://images.unsplash.com/photo-1513104890138-7c749659a591?w=400&h=300&fit=crop",
    cuisine: "Deutsch/Französisch",
    time: 30,
    servings: 2,
    calories: 520,
    difficulty: "Einfach",
    tags: ["Deutsch", "Schnell", "Vegetarisch möglich"],
    ingredients: [
      { name: "Fertiger Flammkuchenteig", amount: "1 Packung" },
      { name: "Crème fraîche", amount: "200g" },
      { name: "Speckwürfel", amount: "150g" },
      { name: "Zwiebeln", amount: "2 Stück" },
      { name: "Muskatnuss", amount: "1 Prise" },
      { name: "Salz & Pfeffer", amount: "nach Geschmack" },
      { name: "Schnittlauch", amount: "1 Bund" },
    ],
    steps: [
      "Ofen auf 230°C vorheizen.",
      "Teig auf Backpapier ausrollen.",
      "Crème fraîche mit Salz, Pfeffer und Muskat verrühren und aufstreichen.",
      "Mit Zwiebelringen und Speck belegen.",
      "12-15 Minuten goldbraun backen.",
      "Mit Schnittlauch bestreuen und sofort servieren.",
    ],
    rating: 4.6,
    source: "Chefkoch",
  },
  {
    id: "7",
    name: "Beef Burger Deluxe",
    description: "Saftiger Rindfleischburger mit Cheddar, karamellisierten Zwiebeln und hausgemachter Sauce",
    image: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=400&h=300&fit=crop",
    cuisine: "Amerikanisch",
    time: 40,
    servings: 4,
    calories: 850,
    difficulty: "Mittel",
    tags: ["Fleisch", "Burger", "Amerikanisch"],
    ingredients: [
      { name: "Rinderhack", amount: "600g" },
      { name: "Brioche Buns", amount: "4 Stück" },
      { name: "Cheddar", amount: "4 Scheiben" },
      { name: "Zwiebeln", amount: "2 Stück" },
      { name: "Butter", amount: "30g" },
      { name: "Salat", amount: "4 Blätter" },
      { name: "Tomate", amount: "2 Stück" },
      { name: "Mayonnaise", amount: "4 EL" },
      { name: "Senf", amount: "2 EL" },
    ],
    steps: [
      "Zwiebeln in Butter 20 Min. bei niedriger Hitze karamellisieren.",
      "Rinderhack würzen und zu 4 Patties formen.",
      "Patties 3-4 Min. pro Seite grillen oder braten.",
      "Kurz vor Ende Cheddar schmelzen lassen.",
      "Buns toasten und mit Sauce bestreichen.",
      "Burger nach Wunsch belegen und servieren.",
    ],
    rating: 4.7,
    source: "HelloFresh",
  },
  {
    id: "8",
    name: "Miso-Ramen",
    description: "Herzhafter japanischer Nudelsuppe mit Miso-Brühe, weichem Ei und Chashu-Schweinefleisch",
    image: "https://images.unsplash.com/photo-1547592166-23ac45744acd?w=400&h=300&fit=crop",
    cuisine: "Japanisch",
    time: 60,
    servings: 2,
    calories: 620,
    difficulty: "Anspruchsvoll",
    tags: ["Suppe", "Japanisch", "Umami"],
    ingredients: [
      { name: "Ramen-Nudeln", amount: "200g" },
      { name: "Miso-Paste", amount: "3 EL" },
      { name: "Schweinefleisch (Bauch)", amount: "300g" },
      { name: "Eier", amount: "2 Stück" },
      { name: "Hühnerbrühe", amount: "1 Liter" },
      { name: "Sojasauce", amount: "2 EL" },
      { name: "Sesam", amount: "1 EL" },
      { name: "Frühlingszwiebeln", amount: "3 Stück" },
      { name: "Bambus-Sprossen", amount: "100g" },
      { name: "Nori-Blätter", amount: "2 Stück" },
    ],
    steps: [
      "Schweinefleisch mit Sojasauce marinieren und 2h im Kühlschrank lassen.",
      "Fleisch im Ofen bei 160°C 90 Min. schmoren.",
      "Eier 6,5 Min. kochen und in Sojasauce einlegen.",
      "Brühe erhitzen, Miso-Paste einrühren.",
      "Nudeln kochen und in Schüsseln geben.",
      "Brühe angießen, Toppings anrichten und servieren.",
    ],
    rating: 4.8,
    source: "BBC Food",
  },
  {
    id: "9",
    name: "Fisch Tacos",
    description: "Knusprige Fisch-Tacos mit Mango-Salsa, Limetten-Sour-Cream und Kohl-Slaw",
    image: "https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=400&h=300&fit=crop",
    cuisine: "Mexikanisch",
    time: 30,
    servings: 4,
    calories: 490,
    difficulty: "Einfach",
    tags: ["Fisch", "Mexikanisch", "Schnell"],
    ingredients: [
      { name: "Kabeljaufilet", amount: "600g" },
      { name: "Kleine Tortillas", amount: "12 Stück" },
      { name: "Mango", amount: "1 Stück" },
      { name: "Rotkohl", amount: "200g" },
      { name: "Saure Sahne", amount: "150ml" },
      { name: "Limetten", amount: "2 Stück" },
      { name: "Koriander", amount: "1 Bund" },
      { name: "Chiliflocken", amount: "1 TL" },
    ],
    steps: [
      "Fisch würzen und in einer Pfanne knusprig braten.",
      "Mango-Salsa aus Mango, Koriander, Limette und Chili mischen.",
      "Kohl-Slaw aus Rotkohl und Limettensaft zubereiten.",
      "Saure Sahne mit Limettensaft und Salz verrühren.",
      "Tortillas kurz erwärmen.",
      "Tacos mit Fisch, Salsa, Slaw und Creme befüllen.",
    ],
    rating: 4.6,
    source: "HelloFresh",
  },
  {
    id: "10",
    name: "Lachs mit Gemüse",
    description: "Ofengebackener Lachs mit buntem Ofengemüse und Zitronenbuttersauce",
    image: "https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=400&h=300&fit=crop",
    cuisine: "International",
    time: 35,
    servings: 2,
    calories: 520,
    difficulty: "Einfach",
    tags: ["Fisch", "Glutenfrei", "Gesund", "Schnell"],
    ingredients: [
      { name: "Lachsfilet", amount: "400g" },
      { name: "Zucchini", amount: "1 Stück" },
      { name: "Paprika", amount: "1 Stück" },
      { name: "Kirschtomaten", amount: "200g" },
      { name: "Butter", amount: "30g" },
      { name: "Zitrone", amount: "1 Stück" },
      { name: "Knoblauch", amount: "2 Zehen" },
      { name: "Dill", amount: "1 Bund" },
    ],
    steps: [
      "Ofen auf 200°C vorheizen.",
      "Gemüse in Stücke schneiden und mit Olivenöl auf Backblech legen.",
      "Lachs auf das Gemüse setzen, würzen.",
      "20-25 Min. im Ofen garen.",
      "Zitronenbutter aus Butter, Zitrone und Knoblauch schmelzen.",
      "Mit Dill und Zitronenbutter servieren.",
    ],
    rating: 4.5,
    source: "BBC Food",
  },
  {
    id: "11",
    name: "Zwiebelrostbraten",
    description: "Saftiges Rinderrostbraten auf einem Bett aus karamellisierten Zwiebeln mit Spätzle",
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=300&fit=crop",
    cuisine: "Deutsch/Schwäbisch",
    time: 55,
    servings: 4,
    calories: 720,
    difficulty: "Anspruchsvoll",
    tags: ["Fleisch", "Deutsch", "Klassiker", "Schwäbisch"],
    ingredients: [
      { name: "Rinderrücken", amount: "800g" },
      { name: "Zwiebeln", amount: "6 Stück" },
      { name: "Spätzle", amount: "400g" },
      { name: "Rotwein", amount: "200ml" },
      { name: "Rinderbrühe", amount: "300ml" },
      { name: "Butter", amount: "60g" },
      { name: "Thymian", amount: "2 Zweige" },
      { name: "Salz & Pfeffer", amount: "nach Geschmack" },
    ],
    steps: [
      "Fleisch in 1cm dicke Scheiben schneiden und kräftig würzen.",
      "In heißem Öl scharf anbraten, beiseite legen.",
      "Zwiebeln in Scheiben schneiden und in Butter goldbraun karamellisieren.",
      "Mit Rotwein ablöschen und reduzieren lassen.",
      "Brühe hinzugeben, Fleisch zurück in die Pfanne.",
      "15 Min. bei niedriger Hitze garen. Mit Spätzle servieren.",
    ],
    rating: 4.8,
    source: "Chefkoch",
  },
  {
    id: "12",
    name: "Vegane Sushi-Bowl",
    description: "Sushi-Reis mit frischem Gemüse, Avocado, Edamame und Sesam-Sojasauce",
    image: "https://images.unsplash.com/photo-1579871494447-9811cf80d66c?w=400&h=300&fit=crop",
    cuisine: "Japanisch",
    time: 25,
    servings: 2,
    calories: 450,
    difficulty: "Einfach",
    tags: ["Vegan", "Vegetarisch", "Japanisch", "Gesund"],
    ingredients: [
      { name: "Sushi-Reis", amount: "300g" },
      { name: "Reisessig", amount: "3 EL" },
      { name: "Avocado", amount: "1 Stück" },
      { name: "Gurke", amount: "1 Stück" },
      { name: "Edamame", amount: "150g" },
      { name: "Karotte", amount: "1 Stück" },
      { name: "Sojasauce", amount: "3 EL" },
      { name: "Sesam", amount: "2 EL" },
      { name: "Nori-Blätter", amount: "2 Stück" },
    ],
    steps: [
      "Sushi-Reis kochen und mit Reisessig und Zucker würzen.",
      "Gemüse in dünne Streifen schneiden oder raspeln.",
      "Edamame auftauen.",
      "Reis in Bowls geben und Gemüse, Avocado, Edamame darauf anrichten.",
      "Nori in Streifen schneiden und dazulegen.",
      "Mit Sojasauce und Sesam beträufeln.",
    ],
    rating: 4.4,
    source: "BBC Food",
  },
  {
    id: "13",
    name: "Currywurst mit Pommes",
    description: "Berliner Kultklassiker: gegrillte Wurst in hausgemachter Currysauce mit knusprigen Pommes",
    image: "https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=400&h=300&fit=crop",
    cuisine: "Deutsch",
    time: 25,
    servings: 2,
    calories: 680,
    difficulty: "Einfach",
    tags: ["Deutsch", "Streetfood", "Schnell"],
    ingredients: [
      { name: "Bratwürste", amount: "4 Stück" },
      { name: "Pommes frites", amount: "400g (TK)" },
      { name: "Tomatenketchup", amount: "200ml" },
      { name: "Currypulver", amount: "2 EL" },
      { name: "Worcestersauce", amount: "1 EL" },
      { name: "Paprikapulver", amount: "1 TL" },
    ],
    steps: [
      "Pommes nach Packungsanleitung knusprig backen.",
      "Currysauce aus Ketchup, Curry, Worcester und Paprika köcheln.",
      "Würste in der Pfanne braten bis sie goldbraun sind.",
      "Würste in Scheiben schneiden.",
      "Currysauce über die Wurst geben.",
      "Mit Pommes servieren und extra Curry darüberstreuen.",
    ],
    rating: 4.5,
    source: "Chefkoch",
  },
  {
    id: "14",
    name: "Griechischer Bauernsalat",
    description: "Erfrischender Salat mit Tomaten, Gurken, Oliven, Feta und Oregano-Olivenöl-Dressing",
    image: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=400&h=300&fit=crop",
    cuisine: "Griechisch",
    time: 15,
    servings: 2,
    calories: 320,
    difficulty: "Einfach",
    tags: ["Salat", "Vegetarisch", "Glutenfrei", "Schnell", "Gesund"],
    ingredients: [
      { name: "Tomaten", amount: "4 Stück" },
      { name: "Gurke", amount: "1 Stück" },
      { name: "Feta", amount: "200g" },
      { name: "Kalamata-Oliven", amount: "100g" },
      { name: "Rote Zwiebel", amount: "1 Stück" },
      { name: "Olivenöl", amount: "4 EL" },
      { name: "Oregano", amount: "1 TL" },
    ],
    steps: [
      "Tomaten und Gurke in grobe Stücke schneiden.",
      "Rote Zwiebel in dünne Ringe schneiden.",
      "Alles in einer Schüssel vermengen.",
      "Feta in Würfel schneiden und darauflegen.",
      "Oliven dazugeben.",
      "Mit Olivenöl und Oregano beträufeln.",
    ],
    rating: 4.3,
    source: "BBC Food",
  },
  {
    id: "15",
    name: "Pad Thai",
    description: "Authentischer thailändischer Wok-Klassiker mit Reisnudeln, Garnelen und Erdnüssen",
    image: "https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=400&h=300&fit=crop",
    cuisine: "Thailändisch",
    time: 25,
    servings: 2,
    calories: 580,
    difficulty: "Mittel",
    tags: ["Asiatisch", "Nudelgericht", "Schnell"],
    ingredients: [
      { name: "Reisnudeln", amount: "200g" },
      { name: "Garnelen", amount: "300g" },
      { name: "Eier", amount: "2 Stück" },
      { name: "Sojasprossen", amount: "100g" },
      { name: "Frühlingszwiebeln", amount: "3 Stück" },
      { name: "Erdnüsse", amount: "50g" },
      { name: "Fischsauce", amount: "3 EL" },
      { name: "Tamarindenpaste", amount: "2 EL" },
      { name: "Limette", amount: "1 Stück" },
    ],
    steps: [
      "Nudeln 30 Min. in warmem Wasser einweichen.",
      "Garnelen in Wok bei starker Hitze anbraten.",
      "Beiseite schieben, Eier scramble braten.",
      "Nudeln hinzufügen, mit Sauce vermengen.",
      "Sojasprossen und Frühlingszwiebeln unterheben.",
      "Mit Erdnüssen und Limette servieren.",
    ],
    rating: 4.7,
    source: "HelloFresh",
  },
  {
    id: "16",
    name: "Hausgemachtes Brot",
    description: "Knuspriges Sauerteigbrot mit krachender Kruste und saftigem Inneren",
    image: "https://images.unsplash.com/photo-1509440159596-0249088772ff?w=400&h=300&fit=crop",
    cuisine: "Deutsch",
    time: 180,
    servings: 8,
    calories: 220,
    difficulty: "Anspruchsvoll",
    tags: ["Backen", "Vegan", "Vegetarisch", "Brot"],
    ingredients: [
      { name: "Weizenmehl Type 550", amount: "400g" },
      { name: "Roggenmehl", amount: "100g" },
      { name: "Sauerteig-Ansatz", amount: "100g" },
      { name: "Salz", amount: "10g" },
      { name: "Wasser", amount: "350ml" },
      { name: "Hefe", amount: "5g" },
    ],
    steps: [
      "Alle Zutaten zu einem Teig verkneten.",
      "2 Stunden bei Raumtemperatur gehen lassen.",
      "Teig falten und formen.",
      "Im Kühlschrank über Nacht kalt führen.",
      "Ofen mit Topf auf 250°C vorheizen.",
      "30 Min. mit Deckel, 15 Min. ohne backen.",
    ],
    rating: 4.6,
    source: "Chefkoch",
  },
  {
    id: "17",
    name: "Shakshuka",
    description: "Nahost-Klassiker: pochierte Eier in würziger Tomaten-Paprika-Sauce mit Feta",
    image: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=400&h=300&fit=crop",
    cuisine: "Nahost",
    time: 25,
    servings: 2,
    calories: 380,
    difficulty: "Einfach",
    tags: ["Vegetarisch", "Glutenfrei", "Frühstück", "Schnell"],
    ingredients: [
      { name: "Eier", amount: "4 Stück" },
      { name: "Gehackte Tomaten", amount: "400g" },
      { name: "Paprika", amount: "2 Stück" },
      { name: "Zwiebel", amount: "1 Stück" },
      { name: "Knoblauch", amount: "3 Zehen" },
      { name: "Kreuzkümmel", amount: "1 TL" },
      { name: "Paprikapulver", amount: "2 TL" },
      { name: "Feta", amount: "100g" },
      { name: "Petersilie", amount: "1 Bund" },
    ],
    steps: [
      "Zwiebeln und Paprika in Olivenöl anbraten.",
      "Knoblauch und Gewürze hinzufügen.",
      "Tomaten dazugeben und 10 Min. köcheln.",
      "Mulden in die Sauce drücken, Eier hineinschlagen.",
      "Abdecken und 5-7 Min. garen.",
      "Mit Feta und Petersilie servieren.",
    ],
    rating: 4.5,
    source: "BBC Food",
  },
  {
    id: "18",
    name: "Margarita Pizza",
    description: "Klassische neapolitanische Pizza mit San-Marzano-Tomaten, Büffelmozzarella und Basilikum",
    image: "https://images.unsplash.com/photo-1513104890138-7c749659a591?w=400&h=300&fit=crop",
    cuisine: "Italienisch",
    time: 45,
    servings: 2,
    calories: 580,
    difficulty: "Mittel",
    tags: ["Pizza", "Vegetarisch", "Italienisch", "Klassiker"],
    ingredients: [
      { name: "Pizzateig", amount: "300g" },
      { name: "San-Marzano-Tomaten", amount: "400g" },
      { name: "Büffelmozzarella", amount: "250g" },
      { name: "Basilikum", amount: "1 Bund" },
      { name: "Olivenöl", amount: "2 EL" },
      { name: "Meersalz", amount: "nach Geschmack" },
    ],
    steps: [
      "Ofen auf 250°C (Grill) vorheizen.",
      "Teig dünn ausrollen.",
      "Tomaten von Hand zerdrücken und gleichmäßig verteilen.",
      "Mozzarella in Stücke reißen und darauflegen.",
      "8-12 Min. backen bis der Rand knusprig ist.",
      "Mit frischem Basilikum und Olivenöl servieren.",
    ],
    rating: 4.8,
    source: "Chefkoch",
  },
  {
    id: "19",
    name: "Linsensuppe mit Croûtons",
    description: "Herzhafte Rote-Linsen-Suppe mit Kokosmilch, Curry und selbstgemachten Croûtons",
    image: "https://images.unsplash.com/photo-1547592166-23ac45744acd?w=400&h=300&fit=crop",
    cuisine: "International",
    time: 35,
    servings: 4,
    calories: 380,
    difficulty: "Einfach",
    tags: ["Vegan", "Vegetarisch", "Suppe", "Glutenfrei"],
    ingredients: [
      { name: "Rote Linsen", amount: "300g" },
      { name: "Kokosmilch", amount: "400ml" },
      { name: "Gemüsebrühe", amount: "800ml" },
      { name: "Zwiebel", amount: "1 Stück" },
      { name: "Knoblauch", amount: "2 Zehen" },
      { name: "Ingwer", amount: "2 cm" },
      { name: "Currypulver", amount: "2 TL" },
      { name: "Baguette", amount: "4 Scheiben" },
    ],
    steps: [
      "Zwiebeln, Knoblauch und Ingwer anschwitzen.",
      "Currypulver hinzufügen und 1 Min. anrösten.",
      "Linsen und Brühe hinzufügen, 20 Min. köcheln.",
      "Kokosmilch einrühren, pürieren.",
      "Baguette in Würfel schneiden und in Öl knusprig braten.",
      "Suppe anrichten und mit Croûtons garnieren.",
    ],
    rating: 4.4,
    source: "BBC Food",
  },
  {
    id: "20",
    name: "Chicken Teriyaki Bowl",
    description: "Zartes Teriyaki-Hähnchen mit Jasminreis, Edamame und Sesam-Gurken-Salat",
    image: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=400&h=300&fit=crop",
    cuisine: "Japanisch-Amerikanisch",
    time: 30,
    servings: 2,
    calories: 540,
    difficulty: "Einfach",
    tags: ["Hähnchen", "Bowl", "Asiatisch", "Schnell"],
    ingredients: [
      { name: "Hähnchenbrust", amount: "400g" },
      { name: "Jasminreis", amount: "250g" },
      { name: "Edamame", amount: "150g" },
      { name: "Sojasauce", amount: "4 EL" },
      { name: "Mirin", amount: "2 EL" },
      { name: "Honig", amount: "1 EL" },
      { name: "Sesam", amount: "1 EL" },
      { name: "Gurke", amount: "1 Stück" },
    ],
    steps: [
      "Reis kochen.",
      "Teriyaki-Sauce aus Soja, Mirin und Honig köcheln.",
      "Hähnchen in Streifen schneiden und in Pfanne braten.",
      "Sauce über Hähnchen geben und karamellisieren lassen.",
      "Gurke in dünne Scheiben schneiden.",
      "Bowl zusammenstellen und mit Sesam garnieren.",
    ],
    rating: 4.6,
    source: "HelloFresh",
  },
];
